# Generated by Django 2.1.5 on 2019-02-23 06:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_engine_no', models.CharField(max_length=100)),
                ('car_registration_no', models.CharField(max_length=100)),
                ('car_consumption_rate', models.CharField(max_length=100)),
                ('car_image', models.ImageField(upload_to='')),
                ('availability', models.CharField(default='AVAILABLE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=500)),
                ('other_complainant', models.CharField(blank=True, max_length=100, null=True)),
                ('forwarded_status', models.CharField(default='NOT FORWARDED', max_length=100)),
                ('handled_status', models.CharField(default='NOT HANDLED', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_next_of_kin', models.CharField(max_length=100)),
                ('driver_next_of_kin_contact', models.CharField(max_length=100)),
                ('next_of_kin_national_id_image', models.ImageField(upload_to='')),
                ('driver_licence_no', models.CharField(max_length=100)),
                ('driver_contact', models.CharField(max_length=100)),
                ('driver_email', models.EmailField(max_length=100)),
                ('driver_image', models.ImageField(upload_to='')),
                ('driver_monthly_payment', models.FloatField(default=1133600.0)),
                ('driver_permit_or_nationalID_image', models.ImageField(upload_to='')),
                ('driver_monthly_payment_ref', models.FloatField(default=0.0)),
                ('attached_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Driver_Payment_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(default='name', max_length=100, null=True)),
                ('driver_car', models.CharField(default='car', max_length=100, null=True)),
                ('amount_paid', models.FloatField(default=0.0, null=True)),
                ('balance', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_payment_Reports_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100, null=True)),
                ('driver_name', models.CharField(default='name', max_length=100, null=True)),
                ('driver_car', models.CharField(default='car', max_length=100, null=True)),
                ('amount_paid', models.FloatField(default=0.0, null=True)),
                ('balance', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('paid_by', models.CharField(max_length=100)),
                ('received_by', models.CharField(max_length=100)),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayments_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('paid_by', models.CharField(max_length=100)),
                ('received_by', models.CharField(max_length=100)),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 2, 23, 6, 40, 8, 118285, tzinfo=utc))),
                ('Salary_Type', models.CharField(choices=[('ALLOWANCE', 'Pay Allowances'), ('Salary', 'Monthly Salary'), ('Advance', 'Pay Advances'), ('Commission', 'Pay Commission')], default='SALARY', max_length=12)),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Month of Pay', max_length=12)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.TextField(default='amount in words', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 2, 23, 6, 40, 8, 118285, tzinfo=utc))),
                ('PaymentMadeTo', models.CharField(default='Canon', max_length=100)),
                ('ReasonForPayment', models.CharField(choices=[('Mechanic', 'Car Repairing'), ('WaterBills', 'Water Bills'), ('Electricity', 'Electricity Bills'), ('URA', 'Paying Revenue')], max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.TextField(default='amount in words', max_length=500)),
                ('ReceivedBy', models.CharField(default='Receiptionist', max_length=100)),
                ('ApprovedBy', models.CharField(default='Manager', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FistName', models.CharField(default='1st name', max_length=150)),
                ('SecondName', models.CharField(default='2nd name', max_length=150)),
                ('Salary', models.IntegerField(default=0)),
                ('Role', models.CharField(choices=[('Developers', 'ICT'), ('Receptionist', 'Rec'), ('Director', 'DIR'), ('Operations', 'CEO'), ('Cashiers', 'Cashier'), ('Executive', 'Exe')], default='MALE', max_length=20)),
                ('Duties', models.TextField(default='ICT', max_length=1000)),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='MALE', max_length=7)),
                ('Contact', models.CharField(default='Tel or Email', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 2, 23, 6, 40, 8, 118285, tzinfo=utc))),
                ('PaymentMadeTo', models.CharField(default='Canon', max_length=100)),
                ('ReasonForPayment', models.TextField(default='Only relatively small expense', max_length=25)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.TextField(default='amount in words', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='abc123@gmail.com', max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, choices=[('Receptionist', 'Receptionist'), ('Operations', 'Operations'), ('Accountant', 'Accountant'), ('Executive', 'Executive')], default='Receptionist', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='salary',
            name='Staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.StaffDetails'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.Driver'),
        ),
    ]
